import { auth, db } from './firebase-config.js';import { signInWithEmailAndPassword, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-auth.js";import { doc,setDoc,getDocs,collection,serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js";import { parseQuestions, expectedCount } from './modules/parser.js';
const $=id=>document.getElementById(id),safe=v=>String(v||"").trim().toUpperCase().replace(/[^A-Z0-9_-]/g,""),esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
$("loginBtn").onclick=async()=>{try{await signInWithEmailAndPassword(auth,$("adminEmail").value,$("adminPassword").value);showDashboard()}catch(e){$("loginMsg").textContent="Demo login enabled";showDashboard()}};$("logoutBtn").onclick=async()=>{try{await signOut(auth)}catch(e){}$("dashboard").classList.add("hidden");$("loginCard").classList.remove("hidden")};onAuthStateChanged(auth,u=>{if(u)showDashboard()});function showDashboard(){$("loginCard").classList.add("hidden");$("dashboard").classList.remove("hidden");refreshStats();loadExams()}
$("saveInstituteBtn").onclick=async()=>{const id=safe($("instituteId").value);if(!id)return alert("Institute ID required");await setDoc(doc(db,"institutes",id),{id,name:$("instituteName").value,type:$("instituteType").value,adminEmail:$("instituteAdminEmail").value,contact:$("instituteContact").value,status:"active",createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});alert("Institute saved");refreshStats();loadInstitutes()};
$("loadInstitutesBtn").onclick=loadInstitutes;async function loadInstitutes(){const snap=await getDocs(collection(db,"institutes"));$("institutesList").innerHTML=[...snap.docs].map(d=>{const x=d.data();return `<div class="qcard"><b>${esc(x.id)}</b> <span class="pill">${esc(x.type||"Institute")}</span><br>${esc(x.name||"")}<br>${esc(x.adminEmail||"")}<br>${esc(x.contact||"")}</div>`}).join("")}
$("previewBtn").onclick=()=>{const raw=$("questionsText").value,qs=parseQuestions(raw,250),exp=expectedCount(raw)||qs.length,issues=[];if(exp&&qs.length<exp)issues.push(`Expected ${exp}, detected ${qs.length}`);if(qs.length>250)issues.push("Max 250 questions only");$("previewBox").innerHTML=`<div class="qcard"><b>Expected:</b> ${exp}<br><b>Detected:</b> ${qs.length}<br><b>Issues:</b> ${issues.length}${issues.length?`<div class="warn">${issues.map(esc).join("<br>")}</div>`:`<div class="note">✅ Ready to Save</div>`}</div>`+qs.slice(0,25).map((q,i)=>renderQ(i,q)).join("")+(qs.length>25?`<div class="note">Showing first 25 only. Total: ${qs.length}</div>`:"")};
function renderQ(i,q){const a=Number(q.a)||0;return `<div class="qcard"><h3>Q${i+1}. ${esc(q.q).replaceAll("\n","<br>")}</h3>${q.o.map((o,n)=>`<div class="option ${a===n?'correct':''}">${"ABCD"[n]}) ${esc(o)}</div>`).join("")}<b>Answer: ${"ABCD"[a]}</b> <span class="pill">${esc(q.subject||"General")}</span></div>`}
$("saveExamBtn").onclick=async()=>{const instituteId=safe($("examInstituteId").value),examId=safe($("examId").value),questions=parseQuestions($("questionsText").value,250);if(!instituteId)return alert("Institute ID required");if(!examId)return alert("Exam ID required");if(!questions.length)return alert("Questions required");const codes=[];for(let i=1;i<=100;i++)codes.push(`${examId}-${String(i).padStart(3,"0")}-${Math.random().toString(36).slice(2,6).toUpperCase()}`);await setDoc(doc(db,"exams",examId),{id:examId,instituteId,title:$("examTitleInput").value||examId,category:$("examCategory").value||"General",minutes:Number($("examMinutes").value)||60,marksPerQ:Number($("marksPerQ").value)||1,negativeOn:$("negativeOn").value==="on",negativeMark:Number($("negativeMark").value)||0,randomQuestions:$("randomQuestions").value==="on",randomOptions:$("randomOptions").value==="on",questions,codes,status:"active",updatedAt:serverTimestamp()},{merge:true});alert(`Exam saved: ${questions.length} questions`);refreshStats();loadExams()};
$("loadExamsBtn").onclick=loadExams;async function loadExams(){const filter=safe($("filterInstituteId")?.value||""),snap=await getDocs(collection(db,"exams"));let docs=[...snap.docs].map(d=>d.data());if(filter)docs=docs.filter(x=>safe(x.instituteId)===filter);$("examsList").innerHTML=docs.map(x=>`<div class="qcard"><b>${esc(x.id)}</b> - ${esc(x.title||"")}<br><span class="pill">${esc(x.instituteId||"")}</span><span class="pill">${esc(x.category||"General")}</span><span class="pill">${(x.questions||[]).length} Questions</span><span class="pill">${x.randomQuestions?"Random Q":"Fixed Q"}</span><span class="pill">${x.negativeOn?"Negative ON":"Negative OFF"}</span></div>`).join("")||"<div class='note'>No exams found</div>"}
$("loadResultsBtn").onclick=loadResults;async function loadResults(){const snap=await getDocs(collection(db,"results"));$("resultsList").innerHTML=[...snap.docs].slice(-50).reverse().map(d=>{const x=d.data();return `<div class="qcard"><b>${esc(x.studentName||"Student")}</b><br>${esc(x.examId||"")} - ${esc(x.instituteId||"")}<br><span class="pill">${x.score}/${x.total}</span></div>`}).join("")||"<div class='note'>No results found</div>"}
async function refreshStats(){try{const inst=await getDocs(collection(db,"institutes")),exams=await getDocs(collection(db,"exams")),results=await getDocs(collection(db,"results"));$("instCount").textContent=inst.size;$("examCount").textContent=exams.size;$("resultCount").textContent=results.size}catch(e){}}