import { db } from './firebase-config.js';import { doc,getDoc,setDoc,serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js";import { shuffleArray } from './modules/parser.js';
const $=id=>document.getElementById(id);let exam=null,questions=[],current=0,answers=[],review=[],remaining=0,timer=null,submitted=false,sessionKey="";
$("startExamBtn").onclick=startExam;$("hallBtn").onclick=showHall;$("prevBtn").onclick=()=>{if(current>0){current--;renderQuestion();saveProgress()}};$("nextBtn").onclick=()=>{if(current<questions.length-1){current++;renderQuestion();saveProgress()}};$("markBtn").onclick=()=>{review[current]=!review[current];renderPalette();saveProgress()};$("clearBtn").onclick=()=>{answers[current]=null;renderQuestion();saveProgress()};$("submitBtn").onclick=()=>submitExam(false);
function showHall(){const inst=$("studentInstituteId").value,exam=$("studentExamId").value,name=$("studentName").value,phone=$("studentPhone").value,photo=$("studentPhoto").value,code=$("studentCode").value||`${exam}-${String(phone||Date.now()).slice(-4)}`;$("studentTicket").innerHTML=`<div class="ticket"><div class="top"><div><h2>Hall Ticket</h2><p><b>Name:</b> ${esc(name)}</p><p><b>Institute:</b> ${esc(inst)}</p><p><b>Exam:</b> ${esc(exam)}</p><p><b>Phone:</b> ${esc(phone)}</p><p><b>Code:</b> ${esc(code)}</p></div>${photo?`<img class="photo" src="${esc(photo)}">`:""}</div><div class="qr">${esc(code)}</div></div>`}
async function startExam(){const instituteId=$("studentInstituteId").value.trim().toUpperCase(),examId=$("studentExamId").value.trim().toUpperCase();if(!instituteId||!examId){$("studentMsg").textContent="Institute ID and Exam ID required";return}sessionKey=`${examId}_${($("studentPhone").value||$("studentName").value||"student").toString()}`;const snap=await getDoc(doc(db,"exams",examId));if(!snap.exists()){$("studentMsg").textContent="Exam not found";return}exam=snap.data();if(String(exam.instituteId||"").toUpperCase()!==instituteId){$("studentMsg").textContent="This exam does not belong to this institute";return}questions=(exam.questions||[]).map((q,idx)=>({...q,_originalIndex:idx}));if(exam.randomQuestions)questions=shuffleArray(questions);if(exam.randomOptions)questions=questions.map(randomizeOptions);if(!questions.length){$("studentMsg").textContent="No questions";return}answers=Array(questions.length).fill(null);review=Array(questions.length).fill(false);remaining=(Number(exam.minutes)||60)*60;await tryResume();$("loginCard").classList.add("hidden");$("examArea").classList.remove("hidden");$("examTitle").textContent=exam.title||exam.id;renderQuestion();tick();timer=setInterval(tick,1000);saveProgress()}
async function tryResume(){try{const s=await getDoc(doc(db,"attempts",sessionKey));if(s.exists()){const d=s.data();if(d.status==="submitted")return;if(Array.isArray(d.answers)&&d.answers.length===questions.length){answers=d.answers;review=Array.isArray(d.review)?d.review:review;current=Number(d.current)||0;remaining=Number(d.remaining)||remaining;$("studentMsg").textContent="Previous progress resumed";}}}catch(e){}}
function randomizeOptions(q){const arr=(q.o||[]).map((txt,i)=>({txt,i})),shuffled=shuffleArray(arr);return {...q,o:shuffled.map(x=>x.txt),a:shuffled.findIndex(x=>x.i===Number(q.a))}}
function renderQuestion(){const q=questions[current];$("questionBox").innerHTML=`<div class="qcard"><h3>Q${current+1}. ${esc(q.q).replaceAll("\n","<br>")}</h3>${(q.o||[]).map((o,i)=>`<button class="${answers[current]===i?'primary':''}" onclick="window.chooseAnswer(${i})">${"ABCD"[i]}) ${esc(o)}</button><br>`).join("")}</div>`;renderPalette();updateCounts()}window.chooseAnswer=i=>{answers[current]=i;renderQuestion();saveProgress()};window.goQ=i=>{current=i;renderQuestion();saveProgress()};
function renderPalette(){$("palette").innerHTML=questions.map((_,i)=>`<button class="${i===current?'current ':''}${answers[i]!==null?'answered':review[i]?'review':''}" onclick="window.goQ(${i})">${i+1}</button>`).join("")}
function updateCounts(){const answered=answers.filter(x=>x!==null).length,rev=review.filter(Boolean).length;$("answeredCount").textContent=`Answered ${answered}`;$("reviewCount").textContent=`Review ${rev}`;$("unansweredCount").textContent=`Unanswered ${questions.length-answered}`}
function tick(){const m=Math.floor(remaining/60),s=remaining%60;$("timer").textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;if(remaining--<=0)submitExam(true);if(remaining%10===0)saveProgress()}
async function saveProgress(){try{await setDoc(doc(db,"attempts",sessionKey),{examId:exam.id,instituteId:exam.instituteId,studentName:$("studentName").value,phone:$("studentPhone").value,answers,review,current,remaining,status:"in-progress",updatedAt:serverTimestamp()},{merge:true})}catch(e){}}
async function submitExam(auto){if(submitted)return;if(!auto&&!confirm("Submit exam?"))return;submitted=true;clearInterval(timer);let correct=0,wrong=0,unanswered=0;questions.forEach((q,i)=>{if(answers[i]===null)unanswered++;else if(answers[i]===Number(q.a))correct++;else wrong++});const marks=Number(exam.marksPerQ)||1,neg=exam.negativeOn?(Number(exam.negativeMark)||0):0,score=(correct*marks)-(wrong*neg),percent=questions.length?((score/(questions.length*marks))*100).toFixed(2):0;await setDoc(doc(db,"results",sessionKey),{examId:exam.id,instituteId:exam.instituteId,studentName:$("studentName").value,phone:$("studentPhone").value,score,total:questions.length,correct,wrong,unanswered,percent,answers,auto,submittedAt:serverTimestamp()});await setDoc(doc(db,"attempts",sessionKey),{status:"submitted",submittedAt:serverTimestamp()},{merge:true});$("examArea").classList.add("hidden");$("resultBox").classList.remove("hidden");$("resultBox").innerHTML=`<h2>Result</h2><h1>${score} / ${questions.length}</h1><p>Percentage: ${percent}%</p><p>Correct: ${correct} | Wrong: ${wrong} | Unanswered: ${unanswered}</p>`}function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;")}