import { db } from './firebase-config.js';
import { doc, getDoc, setDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js";
const $=id=>document.getElementById(id);
let exam=null,questions=[],current=0,answers=[],review=[],remaining=0,timer=null;
$("startExamBtn").onclick=startExam;$("prevBtn").onclick=()=>{if(current>0){current--;renderQuestion()}};$("nextBtn").onclick=()=>{if(current<questions.length-1){current++;renderQuestion()}};$("markBtn").onclick=()=>{review[current]=!review[current];renderPalette()};$("submitBtn").onclick=()=>submitExam(false);
async function startExam(){const examId=$("studentExamId").value.trim().toUpperCase();const snap=await getDoc(doc(db,"exams",examId));if(!snap.exists()){$("studentMsg").textContent="Exam not found";return}exam=snap.data();questions=exam.questions||[];if(!questions.length){$("studentMsg").textContent="No questions";return}answers=Array(questions.length).fill(null);review=Array(questions.length).fill(false);remaining=(Number(exam.minutes)||60)*60;$("loginCard").classList.add("hidden");$("examArea").classList.remove("hidden");$("examTitle").textContent=exam.title||exam.id;renderQuestion();tick();timer=setInterval(tick,1000)}
function renderQuestion(){const q=questions[current];$("questionBox").innerHTML=`<div class="qcard"><h3>Q${current+1}. ${esc(q.q).replaceAll("\n","<br>")}</h3>${(q.o||[]).map((o,i)=>`<button class="${answers[current]===i?'primary':''}" onclick="window.chooseAnswer(${i})">${"ABCD"[i]}) ${esc(o)}</button><br>`).join("")}</div>`;renderPalette()}
window.chooseAnswer=i=>{answers[current]=i;renderQuestion();saveProgress()};window.goQ=i=>{current=i;renderQuestion()};
function renderPalette(){$("palette").innerHTML=questions.map((_,i)=>`<button class="${answers[i]!==null?'success':review[i]?'primary':''}" onclick="window.goQ(${i})">${i+1}</button>`).join("")}
function tick(){const m=Math.floor(remaining/60),s=remaining%60;$("timer").textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;if(remaining--<=0)submitExam(true)}
async function saveProgress(){try{const key=$("studentPhone").value||$("studentName").value||Date.now().toString();await setDoc(doc(db,"attempts",`${exam.id}_${key}`),{examId:exam.id,instituteId:exam.instituteId,studentName:$("studentName").value,phone:$("studentPhone").value,answers,current,remaining,status:"in-progress",updatedAt:serverTimestamp()},{merge:true})}catch(e){}}
async function submitExam(auto){clearInterval(timer);let score=0;questions.forEach((q,i)=>{if(answers[i]===Number(q.a))score++});const key=$("studentPhone").value||$("studentName").value||Date.now().toString();await setDoc(doc(db,"results",`${exam.id}_${key}`),{examId:exam.id,instituteId:exam.instituteId,studentName:$("studentName").value,phone:$("studentPhone").value,score,total:questions.length,answers,auto,submittedAt:serverTimestamp()});$("examArea").classList.add("hidden");$("resultBox").classList.remove("hidden");$("resultBox").innerHTML=`<h2>Result</h2><h1>${score} / ${questions.length}</h1>`}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;")}
